"""M7 Lean exports preserve the closed PA statement and remain reproducible."""

from __future__ import annotations

from dataclasses import FrozenInstanceError
from urllib.parse import unquote

import pytest

from peano_lab.kernel.formulas import Eq, Forall, parse_formula, parse_formula_with_names
from peano_lab.kernel.terms import Var, Zero
from peano_lab.library.lean import (
    LIVE_LEAN_PREFIX,
    LeanExport,
    export_theorem,
    formula_to_lean,
    live_lean_url,
)


def test_terms_quantifiers_and_all_logical_connectives_have_canonical_lean() -> None:
    arithmetic = parse_formula("forall a b. S a + b * 2 = b * 2 + S a")
    logic = parse_formula(
        "forall a. (a = 0 /\\ false) \\/ (exists b. b = a -> false)"
    )

    assert formula_to_lean(arithmetic) == (
        "∀ x : Nat, ∀ y : Nat, "
        "Nat.succ (x) + y * 2 = y * 2 + Nat.succ (x)"
    )
    assert formula_to_lean(logic) == (
        "∀ x : Nat, x = 0 ∧ False ∨ (∃ y : Nat, y = x → False)"
    )


def test_defined_order_is_exported_as_its_exact_existential_definition() -> None:
    formula = parse_formula("forall n m. n <= m")

    assert formula_to_lean(formula) == (
        "∀ x : Nat, ∀ y : Nat, ∃ z : Nat, z + x = y"
    )


def test_formula_renderer_preserves_non_associative_tree_shape() -> None:
    formula = parse_formula("forall x. (x = 0 -> false) -> false")

    assert formula_to_lean(formula) == "∀ x : Nat, (x = 0 → False) → False"


def test_and_or_associativity_is_preserved_exactly_for_lean() -> None:
    left_and = parse_formula("(0 = 0 /\\ 1 = 1) /\\ 2 = 2")
    right_and = parse_formula("0 = 0 /\\ (1 = 1 /\\ 2 = 2)")
    left_or = parse_formula("(0 = 0 \\/ 1 = 1) \\/ 2 = 2")
    right_or = parse_formula("0 = 0 \\/ (1 = 1 \\/ 2 = 2)")

    assert formula_to_lean(left_and) == "(0 = 0 ∧ 1 = 1) ∧ 2 = 2"
    assert formula_to_lean(right_and) == "0 = 0 ∧ 1 = 1 ∧ 2 = 2"
    assert formula_to_lean(left_or) == "(0 = 0 ∨ 1 = 1) ∨ 2 = 2"
    assert formula_to_lean(right_or) == "0 = 0 ∨ 1 = 1 ∨ 2 = 2"


def test_open_and_malformed_de_bruijn_terms_are_rejected() -> None:
    open_formula, names = parse_formula_with_names("n = 0")
    assert names == ("n",)
    with pytest.raises(ValueError, match=r"closed formula.*#0"):
        formula_to_lean(open_formula)
    with pytest.raises(ValueError, match=r"#-1"):
        formula_to_lean(Eq(Var(-1), Zero()))
    with pytest.raises(ValueError, match=r"#True"):
        formula_to_lean(Forall(Forall(Eq(Var(True), Zero()))))
    with pytest.raises(TypeError, match="Formula"):
        formula_to_lean(Zero())  # type: ignore[arg-type]


def test_export_is_namespaced_documented_and_contains_only_a_proof_stub() -> None:
    formula = parse_formula("forall n m. n + m = m + n")
    exported = export_theorem(
        "add_comm",
        formula,
        ("intro n m", "induction m\nsimp [IH]"),
    )

    assert exported == LeanExport(
        name="add_comm",
        statement="∀ x : Nat, ∀ y : Nat, x + y = y + x",
        code=exported.code,
        live_url=exported.live_url,
    )
    assert exported.code == (
        "-- Generated by Peano Lab; the statement is exact, the proof is a stub.\n"
        "namespace PeanoLab\n\n"
        "theorem «add_comm» : ∀ x : Nat, ∀ y : Nat, x + y = y + x := by\n"
        "  -- Peano Lab tactic script:\n"
        "  --   intro n m\n"
        "  --   induction m\n"
        "  --   simp [IH]\n"
        "  -- Replace this stub with a Lean proof to cross-check it.\n"
        "  sorry\n\n"
        "end PeanoLab"
    )
    assert exported.code.count("sorry") == 1
    assert exported.live_url == ""


def test_unproved_legacy_scaffolds_never_expose_a_lean_live_link() -> None:
    exported = export_theorem(
        "zero_add",
        parse_formula("forall n. 0 + n = n"),
        "induction n\nsimp [IH]",
    )

    assert exported.live_url == ""
    assert "sorry" in exported.code
    assert export_theorem(
        "zero_add",
        parse_formula("forall n. 0 + n = n"),
        "induction n\nsimp [IH]",
    ) == exported


def test_low_level_live_url_encodes_an_exact_completed_source() -> None:
    source = "theorem checked : True := True.intro\n"
    url = live_lean_url(source)

    assert url.startswith(LIVE_LEAN_PREFIX)
    assert unquote(url.removeprefix(LIVE_LEAN_PREFIX)) == source


def test_dependency_metadata_is_distinct_from_the_authored_body() -> None:
    exported = export_theorem(
        "add_comm",
        parse_formula("forall n m. n + m = m + n"),
        ("induction n", "simp [zero_add]"),
        dependencies=("zero_add", "add_succ_left"),
    )

    assert "Earlier checked Peano Lab dependencies: zero_add, add_succ_left" in exported.code
    assert "Peano Lab authored tactic body:" in exported.code
    assert "--   induction n" in exported.code
    assert "intro zero_add" not in exported.code


@pytest.mark.parametrize(
    "name",
    [
        "",
        "_",
        "two words",
        "x; #check False",
        "9lives",
    ],
)
def test_unsafe_theorem_names_are_rejected(name: str) -> None:
    with pytest.raises(ValueError, match="ASCII identifier"):
        export_theorem(name, parse_formula("0 = 0"))


@pytest.mark.parametrize(
    "name",
    (
        "theorem",
        "Type",
        "Prop",
        "partial",
        "mutual",
        "syntax",
        "macro",
        "elab",
        "deriving",
        "private",
        "protected",
        "noncomputable",
        "abbrev",
        "universe",
        "variable",
        "include",
        "omit",
        "termination_by",
        "decreasing_by",
        "show",
        "sorry",
        "nomatch",
        "return",
        "try",
        "repeat",
        "coinductive",
        "using",
        "unless",
        "while",
        "for",
        "finally",
        "leading_parser",
        "trailing_parser",
    ),
)
def test_lean_keywords_are_safe_when_the_declaration_name_is_escaped(name: str) -> None:
    exported = export_theorem(name, parse_formula("0 = 0"))

    assert f"theorem «{name}» : 0 = 0 := by" in exported.code


def test_export_value_and_argument_contracts_are_immutable_and_explicit() -> None:
    exported = export_theorem("refl_zero", parse_formula("0 = 0"))
    assert "--   (no script supplied)" in exported.code

    with pytest.raises(FrozenInstanceError):
        exported.code = "changed"  # type: ignore[misc]
    with pytest.raises(TypeError, match="script"):
        export_theorem("refl_zero", parse_formula("0 = 0"), [1])  # type: ignore[list-item]
    for malformed in (
        "zero_add",
        b"",
        b"zero_add",
        bytearray(),
        [1],
        ("zero_add", 1),
    ):
        with pytest.raises(TypeError, match="dependencies"):
            export_theorem(
                "refl_zero",
                parse_formula("0 = 0"),
                dependencies=malformed,  # type: ignore[arg-type]
            )
    with pytest.raises(TypeError, match="text"):
        live_lean_url(None)  # type: ignore[arg-type]
