"""Untrusted hybrid candidate policies for Peano Lab's checked search."""

from .profile import (
    SEMANTIC_PROFILE_FORMAT,
    SEMANTIC_PROFILE_ID,
    SEMANTIC_PROFILE_VERSION,
    SemanticProfileError,
    canonical_profile_theorem,
    semantic_profile,
    semantic_profile_identity,
    semantic_profile_sha256,
    validate_semantic_profile,
    well_scoped_formula,
)

from .result_schema import (
    RESULT_FORMAT,
    RESULT_SCHEMA_ID,
    RESULT_SCHEMA_VERSION,
    HydraResultEvidence,
    HydraResultSchemaError,
    build_checked_proved_evidence,
    build_checked_proved_result,
    build_unknown_evidence,
    build_unknown_result,
    result_schema_identity,
    validate_checked_proved_result,
    validate_result,
    validate_result_preimages,
)

from .macros import (
    MACRO_FORMAT,
    MACRO_PROTOCOL_ID,
    MACRO_PROTOCOL_VERSION,
    Cut,
    Dispatch,
    DispatchBounds,
    Induct,
    Rewrite,
    Split,
    Use,
    Witness,
    compile_macro,
    macro_protocol_identity,
    parse_macro,
    serialize_macro,
)

from .macro_runner import (
    DispatchAdapterIdentity,
    DispatchAdapterRegistration,
    DispatchProtocolError,
    MacroExecution,
    MacroExecutionError,
    MacroOwner,
    MacroTrace,
    execute_macro,
    register_dispatch_subprocess,
    start_macro_session,
)

from .policy import (
    HYDRA_POLICY_VERSION,
    MACRO_ACTION_HEADS,
    FixedCandidatePolicy,
    HeadGate,
    HeadRole,
    HydraCandidatePolicy,
    HydraPortfolioPolicy,
    IdentifiedCandidatePolicy,
    MacroAction,
    NullCandidatePolicy,
    PolicyHead,
    ProposalOutcome,
    ProposalRecord,
    RecordedCandidatePolicy,
    RecordedState,
    ScriptCandidatePolicy,
)


__all__ = [
    "SEMANTIC_PROFILE_FORMAT",
    "SEMANTIC_PROFILE_ID",
    "SEMANTIC_PROFILE_VERSION",
    "SemanticProfileError",
    "canonical_profile_theorem",
    "semantic_profile",
    "semantic_profile_identity",
    "semantic_profile_sha256",
    "validate_semantic_profile",
    "well_scoped_formula",
    "RESULT_FORMAT",
    "RESULT_SCHEMA_ID",
    "RESULT_SCHEMA_VERSION",
    "HydraResultEvidence",
    "HydraResultSchemaError",
    "build_checked_proved_evidence",
    "build_checked_proved_result",
    "build_unknown_evidence",
    "build_unknown_result",
    "result_schema_identity",
    "validate_checked_proved_result",
    "validate_result",
    "validate_result_preimages",
    "MACRO_FORMAT",
    "MACRO_PROTOCOL_ID",
    "MACRO_PROTOCOL_VERSION",
    "Cut",
    "Dispatch",
    "DispatchBounds",
    "Induct",
    "Rewrite",
    "Split",
    "Use",
    "Witness",
    "compile_macro",
    "macro_protocol_identity",
    "parse_macro",
    "serialize_macro",
    "DispatchAdapterIdentity",
    "DispatchAdapterRegistration",
    "DispatchProtocolError",
    "MacroExecution",
    "MacroExecutionError",
    "MacroOwner",
    "MacroTrace",
    "execute_macro",
    "register_dispatch_subprocess",
    "start_macro_session",
    "HYDRA_POLICY_VERSION",
    "MACRO_ACTION_HEADS",
    "FixedCandidatePolicy",
    "HeadGate",
    "HeadRole",
    "HydraCandidatePolicy",
    "HydraPortfolioPolicy",
    "IdentifiedCandidatePolicy",
    "MacroAction",
    "NullCandidatePolicy",
    "PolicyHead",
    "ProposalOutcome",
    "ProposalRecord",
    "RecordedCandidatePolicy",
    "RecordedState",
    "ScriptCandidatePolicy",
]
