"""Immutable hygienic reviewed definitions for Alpha-v21 constructive campaigns.

These parser-only abbreviations are conservative aliases, not predicates,
axioms, kernel primitives, or proof providers.  Every source is generated by
its actual audited candidate helper and parsed into the unchanged
first-order Heyting-arithmetic syntax.  Historical Alpha-v20 ``DefinitionSpec``
objects are reused by identity; stable identifiers ND0012 through ND0027 are
strictly additive and their conceptual dependency DAG is validated eagerly.
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
import sys
from types import MappingProxyType


ROOT = Path(__file__).resolve().parents[1]
PY_ROOT = ROOT / "peano-lab" / "py"
if str(PY_ROOT) not in sys.path:
    sys.path.insert(0, str(PY_ROOT))

from constructive_next_layer_definitions import (  # noqa: E402
    NEXT_LAYER_DEFINITIONS,
    NEXT_LAYER_DEFINITIONS_BY_NAME,
)
from peano_lab.library.bertrand_defined_edition import (  # noqa: E402
    ALL_BERTRAND_DEFINITIONS,
)
from peano_lab.library.binary_modular_exponentiation_candidate import (  # noqa: E402
    binary_doubled_power,
    binary_exponent_split,
    binary_modular_power,
    binary_modular_step,
    binary_modulus_relation,
    binary_odd_power,
    canonical_modular_residue,
)
from peano_lab.library.defined_syntax import DefinitionSpec, _definition  # noqa: E402
from peano_lab.library.euclidean_complexity_candidate import (  # noqa: E402
    euclidean_division,
    euclidean_execution,
    euclidean_halving,
)
from peano_lab.library.matrix_coded_product_candidate import (  # noqa: E402
    affine_matrix_slice_relation,
    matrix_product_cell_relation,
    matrix_product_prefix_relation,
    pointwise_add_prefix_relation,
    signed_dot_product_relation,
    signed_matrix_product_relation,
)


def _construct(
    *,
    identifier: str,
    name: str,
    parameters: tuple[str, ...],
    source: str,
    summary: str,
    dependencies: tuple[str, ...] = (),
) -> DefinitionSpec:
    return _definition(
        stable_id=identifier,
        name=name,
        parameters=parameters,
        template_source=source,
        summary=summary,
        category="constructive_advanced_layer",
        priority="P2",
        conceptual_dependencies=dependencies,
    )


ADVANCED_LAYER_DEFINITIONS: tuple[DefinitionSpec, ...] = (
    _construct(
        identifier="ND0012",
        name="MatrixAffineSlice",
        parameters=("b", "c", "s", "d", "u", "v", "l"),
        source=affine_matrix_slice_relation("b", "c", "s", "d", "u", "v", "l", tag="advanced"),
        summary="A complete beta-coded affine matrix slice whose exact target entry at i equals the source entry at s+d*i.",
        dependencies=("Beta", "Lt"),
    ),
    _construct(
        identifier="ND0013",
        name="MatrixProductCell",
        parameters=("lb", "lc", "rb", "rc", "w", "v", "i", "j", "n"),
        source=matrix_product_cell_relation("lb", "lc", "rb", "rc", "w", "v", "i", "j", "n", tag="advanced"),
        summary="An exact natural matrix multiplication cell with witnessed beta-coded row, column and finite dot product.",
        dependencies=("MatrixAffineSlice", "DotProduct"),
    ),
    _construct(
        identifier="ND0014",
        name="MatrixProductPrefix",
        parameters=("lb", "lc", "rb", "rc", "w", "v", "tb", "tc", "l"),
        source=matrix_product_prefix_relation("lb", "lc", "rb", "rc", "w", "v", "tb", "tc", "l", tag="advanced"),
        summary="Every bounded row-major natural matrix product cell together with its exact coordinate, strict column bound and output beta witness.",
        dependencies=("MatrixProductCell", "Beta", "Lt"),
    ),
    _construct(
        identifier="ND0015",
        name="MatrixPointwiseAdd",
        parameters=("mb", "mc", "sb", "sc", "tb", "tc", "l"),
        source=pointwise_add_prefix_relation("mb", "mc", "sb", "sc", "tb", "tc", "l", tag="advanced"),
        summary="The complete beta-coded pointwise sum of two exact bounded natural vector prefixes.",
        dependencies=("Beta", "Lt"),
    ),
    _construct(
        identifier="ND0016",
        name="SignedDotProduct",
        parameters=("ab", "ac", "db", "dc", "eb", "ec", "fb", "fc", "l", "p", "n"),
        source=signed_dot_product_relation("ab", "ac", "db", "dc", "eb", "ec", "fb", "fc", "l", "p", "n", tag="advanced"),
        summary="The exact positive and negative components of an arbitrary finite signed-vector dot product, witnessed by four natural dot products.",
        dependencies=("DotProduct",),
    ),
    _construct(
        identifier="ND0017",
        name="SignedMatrixProduct",
        parameters=("ab", "ac", "db", "dc", "eb", "ec", "fb", "fc", "w", "v", "r", "pb", "pc", "nb", "nc"),
        source=signed_matrix_product_relation("ab", "ac", "db", "dc", "eb", "ec", "fb", "fc", "w", "v", "r", "pb", "pc", "nb", "nc", tag="advanced"),
        summary="The exact complete signed finite matrix product: four natural coded products and two beta-coded pointwise-summed positive/negative output matrices.",
        dependencies=("MatrixProductPrefix", "MatrixPointwiseAdd"),
    ),
    _construct(
        identifier="ND0018",
        name="EuclideanDivision",
        parameters=("a", "b", "q", "r"),
        source=euclidean_division("a", "b", "q", "r", tag="advanced"),
        summary="A genuine Euclidean division a=b*q+r with strictly bounded natural remainder r<b.",
        dependencies=("Lt",),
    ),
    _construct(
        identifier="ND0019",
        name="EuclideanHalving",
        parameters=("b", "r"),
        source=euclidean_halving("b", "r", tag="advanced"),
        summary="The exact constructive two-step Euclidean descent inequality r+r<b.",
        dependencies=("Lt",),
    ),
    _construct(
        identifier="ND0020",
        name="EuclideanExecution",
        parameters=("a", "b", "g", "k"),
        source=euclidean_execution("a", "b", "g", "k", tag="advanced"),
        summary="A complete beta-coded Euclidean quotient history together with an independently witnessed relational gcd; terminal-state identification is not asserted.",
        dependencies=("ContinuedFractionTrace", "IsGCD"),
    ),
    _construct(
        identifier="ND0021",
        name="BinaryModulus",
        parameters=("m",),
        source=binary_modulus_relation("m", tag="advanced"),
        summary="The exact constructive nontrivial-modulus guard 1<m.",
        dependencies=("Lt",),
    ),
    _construct(
        identifier="ND0022",
        name="BinaryExponentSplit",
        parameters=("e", "h", "b"),
        source=binary_exponent_split("e", "h", "b", tag="advanced"),
        summary="The exact binary decomposition e=2*h+b with an explicit b=0 or b=1 witness.",
    ),
    _construct(
        identifier="ND0023",
        name="CanonicalModularResidue",
        parameters=("m", "a", "r"),
        source=canonical_modular_residue("m", "a", "r", tag="advanced"),
        summary="A strictly bounded canonical natural residue r<m together with exact balanced congruence to a modulo m.",
        dependencies=("Lt", "ModEq"),
    ),
    _construct(
        identifier="ND0024",
        name="BinaryDoubledPower",
        parameters=("a", "h", "e", "u", "z"),
        source=binary_doubled_power("a", "h", "e", "u", "z", tag="advanced"),
        summary="The exact even-exponent prerequisites e=2*h, Pow(a,h,u) and Pow(a,e,z).",
        dependencies=("Pow",),
    ),
    _construct(
        identifier="ND0025",
        name="BinaryOddPower",
        parameters=("a", "h", "e", "u", "z"),
        source=binary_odd_power("a", "h", "e", "u", "z", tag="advanced"),
        summary="The exact odd-exponent prerequisites e=2*h+1, Pow(a,h,u) and Pow(a,e,z).",
        dependencies=("Pow",),
    ),
    _construct(
        identifier="ND0026",
        name="BinaryModularStep",
        parameters=("m", "u", "a", "b", "r"),
        source=binary_modular_step("m", "u", "a", "b", "r", tag="advanced"),
        summary="One exact binary square or square-and-multiply transition with a genuinely canonical reduced output.",
        dependencies=("CanonicalModularResidue",),
    ),
    _construct(
        identifier="ND0027",
        name="BinaryModularPower",
        parameters=("a", "e", "m", "r"),
        source=binary_modular_power("a", "e", "m", "r", tag="advanced"),
        summary="The exact canonical natural residue of the existing beta-coded exponentiation relation Pow(a,e,z).",
        dependencies=("Pow", "CanonicalModularResidue"),
    ),
)


_KNOWN = {definition.name: definition for definition in ALL_BERTRAND_DEFINITIONS}
_SEEN_IDS = {definition.stable_id for definition in ALL_BERTRAND_DEFINITIONS}
if len(_KNOWN) != len(ALL_BERTRAND_DEFINITIONS) or len(_SEEN_IDS) != len(_KNOWN):
    raise ValueError("the reviewed immutable base definition registry repeats an identity")
for definition in NEXT_LAYER_DEFINITIONS:
    if (
        definition.name in _KNOWN
        or definition.stable_id in _SEEN_IDS
        or NEXT_LAYER_DEFINITIONS_BY_NAME[definition.name] is not definition
    ):
        raise ValueError("an immutable Alpha-v20 definition lost its exact shared identity")
    if len(set(definition.conceptual_dependencies)) != len(definition.conceptual_dependencies):
        raise ValueError("an immutable Alpha-v20 definition repeats a dependency")
    if not set(definition.conceptual_dependencies) <= set(_KNOWN):
        raise ValueError("an immutable Alpha-v20 definition has an unknown or cyclic dependency")
    _KNOWN[definition.name] = definition
    _SEEN_IDS.add(definition.stable_id)

for offset, definition in enumerate(ADVANCED_LAYER_DEFINITIONS, start=12):
    if definition.stable_id != f"ND{offset:04d}":
        raise ValueError("advanced definition stable identifiers must be contiguous and additive")
    if definition.name in _KNOWN or definition.stable_id in _SEEN_IDS:
        raise ValueError("advanced definitions repeat an immutable reviewed name or stable identity")
    dependencies = definition.conceptual_dependencies
    if len(dependencies) != len(set(dependencies)):
        raise ValueError("an advanced definition repeats a conceptual dependency")
    if not set(dependencies) <= set(_KNOWN):
        raise ValueError("an advanced definition has an unknown, forward or circular dependency")
    _KNOWN[definition.name] = definition
    _SEEN_IDS.add(definition.stable_id)

_ADVANCED_BY_NAME = {definition.name: definition for definition in ADVANCED_LAYER_DEFINITIONS}
ADVANCED_LAYER_DEFINITIONS_BY_NAME: Mapping[str, DefinitionSpec] = MappingProxyType(
    _ADVANCED_BY_NAME
)
ALL_CONSTRUCTIVE_DEFINITIONS_BY_NAME: Mapping[str, DefinitionSpec] = MappingProxyType(
    _KNOWN
)
ADVANCED_LAYER_REGISTRIES: tuple[tuple[str, tuple[DefinitionSpec, ...]], ...] = (
    (
        "matrix-coded-products",
        tuple(ADVANCED_LAYER_DEFINITIONS[:6]),
    ),
    (
        "euclidean-complexity",
        tuple(ADVANCED_LAYER_DEFINITIONS[6:9]),
    ),
    (
        "binary-modular-exponentiation",
        tuple(ADVANCED_LAYER_DEFINITIONS[9:]),
    ),
)
if tuple(definition for _, group in ADVANCED_LAYER_REGISTRIES for definition in group) != (
    ADVANCED_LAYER_DEFINITIONS
):
    raise ValueError("advanced definition registry partition changed")


__all__ = (
    "ADVANCED_LAYER_DEFINITIONS",
    "ADVANCED_LAYER_DEFINITIONS_BY_NAME",
    "ADVANCED_LAYER_REGISTRIES",
    "ALL_CONSTRUCTIVE_DEFINITIONS_BY_NAME",
)
