"""Frozen Lean tactic encyclopedia for the browser ``ch tactic`` command.

Generated from the desktop ``lambda_lab/lab/curry_howard/tactics.py`` with
the i18n keys (``ch.tactic.<name>.{summary,lambda_effect,goal_effect,when}``)
resolved to their English strings. The desktop title says "22 tactics"; the
list has since grown to 27 entries and the wording is kept as-is for
faithfulness. Do not edit by hand; regenerate from the desktop sources.
"""

# (name, summary, lambda_effect, goal_effect, when, example_goal, example_after)
TACTICS = [
    ("intro",
     "Introduces the assumption of an implication as a named hypothesis.",
     "Wraps the goal in a new lambda-binder (e.g. `fun p => ?`).",
     "Turns goal `A -> B` into `B` with `x : A` in the context.",
     "When the goal is an implication or a Pi-type.",
     "P → Q", "(p : P) ⊢ Q"),
    ("intros",
     "Introduces all hypotheses from a chain of implications at once.",
     "Adds several lambda-binders `fun p q r => ?` in one step.",
     "Turns `A -> B -> C` into goal `C` with `A`, `B` in the context.",
     "When the goal has several stacked implications or quantifiers.",
     "P → Q → R", "(p : P) (q : Q) ⊢ R"),
    ("exact",
     "Closes the goal by providing an exact term of the same type.",
     "Plugs the given term into the hole `?` of the partial proof.",
     "The goal disappears from the list when the types match.",
     "When you already know the term that proves the goal.",
     "(p : P) ⊢ P", "(closed)"),
    ("apply",
     "Applies a function (implication), reducing the goal to its arguments.",
     "Builds an application `f ?` and leaves holes for the arguments of `f`.",
     "Instead of `Q` the goal becomes `P`, when `f : P -> Q`.",
     "When you know a function whose codomain matches the goal.",
     "(f : P → Q) ⊢ Q", "⊢ P"),
    ("refine",
     "Plugs in a term with holes `?_` and opens a subgoal for each hole.",
     "Enriches the partial term with a skeleton; holes remain to fill.",
     "One goal splits into as many subgoals as there are `?_` holes.",
     "When you know the proof shape but want to defer some details.",
     "⊢ A ∧ B", "⊢ A   ⊢ B"),
    ("rfl",
     "Closes an equality goal `a = a` by reflexivity.",
     "Inserts the canonical proof `Eq.refl a` into the hole.",
     "Goal `a = a` disappears; nothing more to do.",
     "When both sides of the equality are definitionally identical.",
     "⊢ a = a", "(closed)"),
    ("cases",
     "Splits a hypothesis into cases (e.g. left/right for a disjunction).",
     "Builds a `match` or several branches in the partial term.",
     "One goal becomes several subgoals, one per constructor.",
     "When a hypothesis has an inductive type (`Or`, `Nat`, `Sum`, ...).",
     "(h : A ∨ B) ⊢ C", "(ha : A) ⊢ C  /  (hb : B) ⊢ C"),
    ("rcases",
     "Enhanced `cases` with patterns: splits and names in one step.",
     "Builds a nested `match` with named bindings.",
     "A conjunction `A and B` yields `ha`, `hb` immediately.",
     "When you want to combine several splits and name the parts at once.",
     "(h : A ∧ B) ⊢ C", "(ha : A) (hb : B) ⊢ C"),
    ("induction",
     "Induction over an inductive type (e.g. on `Nat` with base and step).",
     "Builds a recursor `Nat.rec` (or analogue) as the term skeleton.",
     "Goal `P n` splits into `P 0` and `P n -> P (n+1)`.",
     "When you must prove a property for all elements of an inductive type.",
     "(n : Nat) ⊢ P n", "P 0  /  P n → P (n+1)"),
    ("by_contra",
     "Proof by contradiction: assume `not P` and derive a contradiction.",
     "Introduces `Classical.byContradiction` and a new hypothesis `h : not P`.",
     "Instead of `P` the goal becomes `False` with `h : not P` in context.",
     "When direct construction fails and you need classical logic.",
     "⊢ P", "(h : ¬P) ⊢ False"),
    ("contradiction",
     "Closes the goal when the context has both `h : P` and `not h : not P`.",
     "Inserts `absurd h not_h` as a complete term.",
     "Any goal disappears - ex falso sequitur quodlibet.",
     "When you see a pair `P` and `not P` (or `False`) in the hypotheses.",
     "(h1 : P) (h2 : ¬P) ⊢ Q", "(closed)"),
    ("tauto",
     "Decides classical propositional tautologies.",
     "Builds the term automatically - it is not shown directly.",
     "The goal is closed (or the tactic fails outright).",
     "When the goal is a tautology built from `and`, `or`, `not`, `->`, `<->`.",
     "⊢ P ∨ ¬P", "(closed via classical)"),
    ("simp",
     "Simplifies the goal by applying lemmas tagged `@[simp]`.",
     "Inserts a chain of rewrites; the final term is assembled by `simp`.",
     "The goal becomes canonical form; often closes by itself.",
     "When the goal can be reduced to truth by known rewrites.",
     "⊢ a + 0 = a", "(closed by simp lemma)"),
    ("rw",
     "Rewrites occurrences using an equality `h : a = b`.",
     "Inserts `Eq.mpr` or `Eq.subst` into the partial term.",
     "In the goal each `a` becomes `b` (or vice versa with `<-`).",
     "When you have an equality and want to apply it to a goal or hypothesis.",
     "(h : a = b) ⊢ f a = f b", "⊢ f b = f b"),
    ("calc",
     "Step-by-step chained proof, e.g. `a = b = c < d`.",
     "Builds a term using `Trans.trans` or `Eq.trans` for each link.",
     "The goal decomposes into consecutive small inequality/equality steps.",
     "When you chain inequalities or multi-step equalities.",
     "⊢ a < c", "step-by-step chain a < b < c"),
    ("use",
     "Supplies a witness for an existential goal `exists x, P x`.",
     "Builds a pair `<witness, ?>` leaving a hole for the proof of `P witness`.",
     "Goal `exists x, P x` turns into `P witness`.",
     "When the goal is existential and you know a concrete witness.",
     "⊢ ∃ n, n + 0 = n", "⊢ 0 + 0 = 0  (after use 0)"),
    ("constructor",
     "Picks the first constructor of an inductive type (e.g. `And.intro`).",
     "Inserts `Foo.mk ?a ?b` with holes for the fields.",
     "Goal `A and B` splits into `A` and `B`.",
     "When the goal type has one canonical constructor (`And`, `Iff`, ...).",
     "⊢ A ∧ B", "⊢ A   ⊢ B"),
    ("left",
     "Chooses the left branch of a disjunction `A or B`.",
     "Inserts `Or.inl ?` at the hole.",
     "Goal `A or B` simplifies to `A`.",
     "When you want to prove the left side of the disjunction.",
     "⊢ A ∨ B", "⊢ A"),
    ("right",
     "Chooses the right branch of a disjunction `A or B`.",
     "Inserts `Or.inr ?` at the hole.",
     "Goal `A or B` simplifies to `B`.",
     "When you want to prove the right side of the disjunction.",
     "⊢ A ∨ B", "⊢ B"),
    ("exists",
     "Shorthand for `use` on existential goals.",
     "Inserts the constructor `Exists.intro witness ?` into the partial term.",
     "Goal `exists x, P x` reduces to `P witness`.",
     "When you have a witness and prefer the short syntax over `use`.",
     "⊢ ∃ x, P x", "⊢ P <witness>"),
    ("assumption",
     "Searches the context for a hypothesis matching the goal and uses it.",
     "Plugs the name of the matching hypothesis into the hole.",
     "The goal disappears if a matching hypothesis was found.",
     "When the goal already appears verbatim in the context.",
     "(h : P) ⊢ P", "(closed)"),
    ("decide",
     "Decides a decidable goal by computation (e.g. `2 + 2 = 4`).",
     "Inserts `Decidable.decide` with a proof by reflection.",
     "The goal closes by computation or the tactic fails.",
     "When the goal has type `Decidable` (number equality, boolean predicate).",
     "⊢ 2 + 2 = 4", "(closed by reflection)"),
    ("omega",
     "Decision procedure for Presburger arithmetic (Nat/Int).",
     "Inserts a linear-arithmetic certificate or fails.",
     "Closes the goal if it reduces to linear (in)equalities.",
     "Linear (in)equalities over Nat/Int (a + b = b + a, n ≤ n + 1).",
     "(a b : Nat) ⊢ a + b = b + a", "(closed by Presburger)"),
    ("ring",
     "Normalises expressions in a commutative (semi)ring (equality).",
     "Inserts an equality proof after reducing to canonical form.",
     "Closes the equality when both sides are equal in the ring language.",
     "Polynomial identities: (a+b)^2 = a^2 + 2ab + b^2.",
     "⊢ (a + b)^2 = a^2 + 2*a*b + b^2", "(closed by ring normalisation)"),
    ("linarith",
     "Linear arithmetic over an ordered field (≤, <, =).",
     "Builds a linear combination of hypotheses that closes the goal.",
     "The goal closes if it follows linearly from the hypotheses.",
     "Transitive inequalities, sums/subtractions among hypotheses.",
     "(h1 : a ≤ b) (h2 : b ≤ c) ⊢ a ≤ c", "(closed by linear arithmetic)"),
    ("norm_num",
     "Normalises numeric expressions (multiplication, division, powers).",
     "Replaces the goal with its numerically-normalised form.",
     "The goal closes after computing the literal values.",
     "Concrete numbers: 2 + 3 * 4 = 14, sqrt 9 = 3.",
     "⊢ 2 + 3 * 4 = 14", "(closed by numeric normalisation)"),
    ("trivial",
     "Tries rfl, assumption, decide — universal first attempt.",
     "Inserts a term if any of the simple tactics succeeds.",
     "The goal closes or the tactic fails (no progress).",
     "When the goal is obvious: True, x = x, a hypothesis in context.",
     "⊢ True", "(closed)"),
]

_FIELDS = ("name", "summary", "lambda_effect", "goal_effect", "when",
           "example_goal", "example_after")

TACTIC_MAP = {row[0]: dict(zip(_FIELDS, row)) for row in TACTICS}


def names():
    return [row[0] for row in TACTICS]


def lookup(name):
    return TACTIC_MAP.get(name)
