"""Frozen data for the browser ``prove`` family (Curry-Howard proof builder).

Generated from the desktop Lambda Lab sources:

* ``lab/curry_howard/tactics.py``  - the Lean 4 tactic encyclopedia (+ Mathlib lemma cheat sheet),
* ``lab/curry_howard/library.py``  - the canonical combinator library,
* ``lab/i18n.py``                  - the English message strings for the builder UI.

Plain dicts/lists only - no YAML/JSON parsing at runtime, stdlib only.
"""

STRINGS = {'ch.lib.list_title': 'Combinator catalogue',
 'ch.lib.col.name': 'Name',
 'ch.lib.col.aliases': 'Aliases',
 'ch.lib.col.lambda': 'lambda-term',
 'ch.lib.col.type': 'Type',
 'ch.lib.col.desc': 'What it does',
 'ch.lib.unknown': 'Unknown combinator `{name}`. Type `prove lib` to see the list.',
 'ch.lib.entry_title': 'Combinator {name}',
 'ch.lib.row.lambda': 'lambda',
 'ch.lib.row.type': 'Type',
 'ch.lib.row.lean': 'Lean',
 'ch.lib.row.aliases': 'Aliases',
 'ch.lib.row.untypeable': '(not typeable in STLC)',
 'ch.tactic.usage': 'Usage: prove tactic [name]. Without argument prints the catalogue of '
                    'tactics.',
 'ch.tactic.list_title': 'Encyclopedia of Lean 4 tactics',
 'ch.tactic.col.name': 'Tactic',
 'ch.tactic.col.summary': 'Short description',
 'ch.tactic.unknown': 'Unknown tactic `{name}`. Run `prove tactic` to see the list.',
 'ch.tactic.entry_title': 'Tactic {name}',
 'ch.tactic.row.summary': 'Summary',
 'ch.tactic.row.lambda': 'On the lambda-term',
 'ch.tactic.row.goal': 'On the goal',
 'ch.tactic.row.when': 'When to apply',
 'ch.tactic.row.example_goal': 'Example - goal',
 'ch.tactic.row.example_after': 'After the tactic',
 'ch.build.usage': 'Usage: prove <type>, e.g. `prove P -> P`.',
 'ch.build.title': 'Proof builder',
 'ch.build.goal_label': 'Goal {idx}/{total}',
 'ch.build.context_label': 'Context',
 'ch.build.target_label': 'Target',
 'ch.build.term_label': 'Term',
 'ch.build.empty_context': '(empty)',
 'ch.build.tactics_hint': 'Tactics: intro [name], exact <term>, apply <term>, assumption, '
                          'refine <term>, hint, undo, qed, abort. Type `t` for a cheat sheet.',
 'ch.build.tactics_ref.title': 'Cheat sheet: builder tactic syntax',
 'ch.build.tactics_ref.meta.hint': 'Suggests the next step (proof search).',
 'ch.build.tactics_ref.meta.undo': 'Undo the last tactic.',
 'ch.build.tactics_ref.meta.done': 'Finish (when all goals are closed).',
 'ch.build.tactics_ref.meta.quit': 'Leave the builder.',
 'ch.build.tactics_ref.meta.show': 'Show the current proof state.',
 'ch.build.tactics_ref.meta.tactics': 'Show this cheat sheet.',
 'ch.build.prompt': '[ch.build]> ',
 'ch.build.unknown_tactic': 'Unknown tactic `{name}`. Type `hint` for a suggestion or `quit` '
                            'to exit.',
 'ch.build.no_more_goals': 'All goals closed.',
 'ch.build.undo_done': 'Last step undone.',
 'ch.build.history_empty': 'History is empty - nothing to undo.',
 'ch.build.tactic_error': 'Tactic error: {error}',
 'ch.build.parse_error': 'Cannot parse type: {error}',
 'ch.build.final_term': 'Final lambda-term',
 'ch.build.lean_theorem': 'Lean theorem',
 'ch.build.hint_suggest': 'Hint: try `exact {term}`.',
 'ch.build.hint_none': 'No automatic hint for the current goal.',
 'ch.build.bye': 'Leaving the builder.',
 'ch.build.goal_not_implication': 'Goal `{target}` is not an implication - `intro` does not '
                                  'apply here.',
 'ch.build.exact_needs_arg': 'Tactic `exact` needs an argument, e.g. `exact p`.',
 'ch.build.apply_needs_arg': 'Tactic `apply` needs an argument (the function to apply).',
 'ch.build.refine_needs_arg': 'Tactic `refine` needs a term with holes `?_`.',
 'ch.build.exact_type_mismatch': 'Term `{term}` has type `{got}` but the goal is `{want}`.',
 'ch.build.apply_not_implication': '`{term}` is not a function - `apply` needs an implication.',
 'ch.build.unknown_term': 'I do not know term `{term}` in the current context.',
 'ch.build.assumption_no_match': 'No hypothesis matches the goal `{target}`.',
 'ch.build.done_without_close': 'There are still open goals - cannot finish.',
 'games.runner.tactics_ref.no_doc': '(no encyclopedia entry)',
 'games.runner.tactics_ref.col.name': 'Tactic',
 'games.runner.tactics_ref.col.what': 'What it does',
 'games.runner.tactics_ref.col.before': 'Example goal',
 'games.runner.tactics_ref.col.after': 'After tactic'}

TACTICS = [{'name': 'intro',
  'summary': 'Introduces the assumption of an implication as a named hypothesis.',
  'lambda_effect': 'Wraps the goal in a new lambda-binder (e.g. `fun p => ?`).',
  'goal_effect': 'Turns goal `A -> B` into `B` with `x : A` in the context.',
  'when': 'When the goal is an implication or a Pi-type.',
  'example_goal': 'P → Q',
  'example_after': '(p : P) ⊢ Q'},
 {'name': 'intros',
  'summary': 'Introduces all hypotheses from a chain of implications at once.',
  'lambda_effect': 'Adds several lambda-binders `fun p q r => ?` in one step.',
  'goal_effect': 'Turns `A -> B -> C` into goal `C` with `A`, `B` in the context.',
  'when': 'When the goal has several stacked implications or quantifiers.',
  'example_goal': 'P → Q → R',
  'example_after': '(p : P) (q : Q) ⊢ R'},
 {'name': 'exact',
  'summary': 'Closes the goal by providing an exact term of the same type.',
  'lambda_effect': 'Plugs the given term into the hole `?` of the partial proof.',
  'goal_effect': 'The goal disappears from the list when the types match.',
  'when': 'When you already know the term that proves the goal.',
  'example_goal': '(p : P) ⊢ P',
  'example_after': '(closed)'},
 {'name': 'apply',
  'summary': 'Applies a function (implication), reducing the goal to its arguments.',
  'lambda_effect': 'Builds an application `f ?` and leaves holes for the arguments of `f`.',
  'goal_effect': 'Instead of `Q` the goal becomes `P`, when `f : P -> Q`.',
  'when': 'When you know a function whose codomain matches the goal.',
  'example_goal': '(f : P → Q) ⊢ Q',
  'example_after': '⊢ P'},
 {'name': 'refine',
  'summary': 'Plugs in a term with holes `?_` and opens a subgoal for each hole.',
  'lambda_effect': 'Enriches the partial term with a skeleton; holes remain to fill.',
  'goal_effect': 'One goal splits into as many subgoals as there are `?_` holes.',
  'when': 'When you know the proof shape but want to defer some details.',
  'example_goal': '⊢ A ∧ B',
  'example_after': '⊢ A   ⊢ B'},
 {'name': 'rfl',
  'summary': 'Closes an equality goal `a = a` by reflexivity.',
  'lambda_effect': 'Inserts the canonical proof `Eq.refl a` into the hole.',
  'goal_effect': 'Goal `a = a` disappears; nothing more to do.',
  'when': 'When both sides of the equality are definitionally identical.',
  'example_goal': '⊢ a = a',
  'example_after': '(closed)'},
 {'name': 'cases',
  'summary': 'Splits a hypothesis into cases (e.g. left/right for a disjunction).',
  'lambda_effect': 'Builds a `match` or several branches in the partial term.',
  'goal_effect': 'One goal becomes several subgoals, one per constructor.',
  'when': 'When a hypothesis has an inductive type (`Or`, `Nat`, `Sum`, ...).',
  'example_goal': '(h : A ∨ B) ⊢ C',
  'example_after': '(ha : A) ⊢ C  /  (hb : B) ⊢ C'},
 {'name': 'rcases',
  'summary': 'Enhanced `cases` with patterns: splits and names in one step.',
  'lambda_effect': 'Builds a nested `match` with named bindings.',
  'goal_effect': 'A conjunction `A and B` yields `ha`, `hb` immediately.',
  'when': 'When you want to combine several splits and name the parts at once.',
  'example_goal': '(h : A ∧ B) ⊢ C',
  'example_after': '(ha : A) (hb : B) ⊢ C'},
 {'name': 'induction',
  'summary': 'Induction over an inductive type (e.g. on `Nat` with base and step).',
  'lambda_effect': 'Builds a recursor `Nat.rec` (or analogue) as the term skeleton.',
  'goal_effect': 'Goal `P n` splits into `P 0` and `P n -> P (n+1)`.',
  'when': 'When you must prove a property for all elements of an inductive type.',
  'example_goal': '(n : Nat) ⊢ P n',
  'example_after': 'P 0  /  P n → P (n+1)'},
 {'name': 'by_contra',
  'summary': 'Proof by contradiction: assume `not P` and derive a contradiction.',
  'lambda_effect': 'Introduces `Classical.byContradiction` and a new hypothesis `h : not P`.',
  'goal_effect': 'Instead of `P` the goal becomes `False` with `h : not P` in context.',
  'when': 'When direct construction fails and you need classical logic.',
  'example_goal': '⊢ P',
  'example_after': '(h : ¬P) ⊢ False'},
 {'name': 'contradiction',
  'summary': 'Closes the goal when the context has both `h : P` and `not h : not P`.',
  'lambda_effect': 'Inserts `absurd h not_h` as a complete term.',
  'goal_effect': 'Any goal disappears - ex falso sequitur quodlibet.',
  'when': 'When you see a pair `P` and `not P` (or `False`) in the hypotheses.',
  'example_goal': '(h1 : P) (h2 : ¬P) ⊢ Q',
  'example_after': '(closed)'},
 {'name': 'tauto',
  'summary': 'Decides classical propositional tautologies.',
  'lambda_effect': 'Builds the term automatically - it is not shown directly.',
  'goal_effect': 'The goal is closed (or the tactic fails outright).',
  'when': 'When the goal is a tautology built from `and`, `or`, `not`, `->`, `<->`.',
  'example_goal': '⊢ P ∨ ¬P',
  'example_after': '(closed via classical)'},
 {'name': 'simp',
  'summary': 'Simplifies the goal by applying lemmas tagged `@[simp]`.',
  'lambda_effect': 'Inserts a chain of rewrites; the final term is assembled by `simp`.',
  'goal_effect': 'The goal becomes canonical form; often closes by itself.',
  'when': 'When the goal can be reduced to truth by known rewrites.',
  'example_goal': '⊢ a + 0 = a',
  'example_after': '(closed by simp lemma)'},
 {'name': 'rw',
  'summary': 'Rewrites occurrences using an equality `h : a = b`.',
  'lambda_effect': 'Inserts `Eq.mpr` or `Eq.subst` into the partial term.',
  'goal_effect': 'In the goal each `a` becomes `b` (or vice versa with `<-`).',
  'when': 'When you have an equality and want to apply it to a goal or hypothesis.',
  'example_goal': '(h : a = b) ⊢ f a = f b',
  'example_after': '⊢ f b = f b'},
 {'name': 'calc',
  'summary': 'Step-by-step chained proof, e.g. `a = b = c < d`.',
  'lambda_effect': 'Builds a term using `Trans.trans` or `Eq.trans` for each link.',
  'goal_effect': 'The goal decomposes into consecutive small inequality/equality steps.',
  'when': 'When you chain inequalities or multi-step equalities.',
  'example_goal': '⊢ a < c',
  'example_after': 'step-by-step chain a < b < c'},
 {'name': 'use',
  'summary': 'Supplies a witness for an existential goal `exists x, P x`.',
  'lambda_effect': 'Builds a pair `<witness, ?>` leaving a hole for the proof of `P witness`.',
  'goal_effect': 'Goal `exists x, P x` turns into `P witness`.',
  'when': 'When the goal is existential and you know a concrete witness.',
  'example_goal': '⊢ ∃ n, n + 0 = n',
  'example_after': '⊢ 0 + 0 = 0  (after use 0)'},
 {'name': 'constructor',
  'summary': 'Picks the first constructor of an inductive type (e.g. `And.intro`).',
  'lambda_effect': 'Inserts `Foo.mk ?a ?b` with holes for the fields.',
  'goal_effect': 'Goal `A and B` splits into `A` and `B`.',
  'when': 'When the goal type has one canonical constructor (`And`, `Iff`, ...).',
  'example_goal': '⊢ A ∧ B',
  'example_after': '⊢ A   ⊢ B'},
 {'name': 'left',
  'summary': 'Chooses the left branch of a disjunction `A or B`.',
  'lambda_effect': 'Inserts `Or.inl ?` at the hole.',
  'goal_effect': 'Goal `A or B` simplifies to `A`.',
  'when': 'When you want to prove the left side of the disjunction.',
  'example_goal': '⊢ A ∨ B',
  'example_after': '⊢ A'},
 {'name': 'right',
  'summary': 'Chooses the right branch of a disjunction `A or B`.',
  'lambda_effect': 'Inserts `Or.inr ?` at the hole.',
  'goal_effect': 'Goal `A or B` simplifies to `B`.',
  'when': 'When you want to prove the right side of the disjunction.',
  'example_goal': '⊢ A ∨ B',
  'example_after': '⊢ B'},
 {'name': 'exists',
  'summary': 'Shorthand for `use` on existential goals.',
  'lambda_effect': 'Inserts the constructor `Exists.intro witness ?` into the partial term.',
  'goal_effect': 'Goal `exists x, P x` reduces to `P witness`.',
  'when': 'When you have a witness and prefer the short syntax over `use`.',
  'example_goal': '⊢ ∃ x, P x',
  'example_after': '⊢ P <witness>'},
 {'name': 'assumption',
  'summary': 'Searches the context for a hypothesis matching the goal and uses it.',
  'lambda_effect': 'Plugs the name of the matching hypothesis into the hole.',
  'goal_effect': 'The goal disappears if a matching hypothesis was found.',
  'when': 'When the goal already appears verbatim in the context.',
  'example_goal': '(h : P) ⊢ P',
  'example_after': '(closed)'},
 {'name': 'decide',
  'summary': 'Decides a decidable goal by computation (e.g. `2 + 2 = 4`).',
  'lambda_effect': 'Inserts `Decidable.decide` with a proof by reflection.',
  'goal_effect': 'The goal closes by computation or the tactic fails.',
  'when': 'When the goal has type `Decidable` (number equality, boolean predicate).',
  'example_goal': '⊢ 2 + 2 = 4',
  'example_after': '(closed by reflection)'},
 {'name': 'omega',
  'summary': 'Decision procedure for Presburger arithmetic (Nat/Int).',
  'lambda_effect': 'Inserts a linear-arithmetic certificate or fails.',
  'goal_effect': 'Closes the goal if it reduces to linear (in)equalities.',
  'when': 'Linear (in)equalities over Nat/Int (a + b = b + a, n ≤ n + 1).',
  'example_goal': '(a b : Nat) ⊢ a + b = b + a',
  'example_after': '(closed by Presburger)'},
 {'name': 'ring',
  'summary': 'Normalises expressions in a commutative (semi)ring (equality).',
  'lambda_effect': 'Inserts an equality proof after reducing to canonical form.',
  'goal_effect': 'Closes the equality when both sides are equal in the ring language.',
  'when': 'Polynomial identities: (a+b)^2 = a^2 + 2ab + b^2.',
  'example_goal': '⊢ (a + b)^2 = a^2 + 2*a*b + b^2',
  'example_after': '(closed by ring normalisation)'},
 {'name': 'linarith',
  'summary': 'Linear arithmetic over an ordered field (≤, <, =).',
  'lambda_effect': 'Builds a linear combination of hypotheses that closes the goal.',
  'goal_effect': 'The goal closes if it follows linearly from the hypotheses.',
  'when': 'Transitive inequalities, sums/subtractions among hypotheses.',
  'example_goal': '(h1 : a ≤ b) (h2 : b ≤ c) ⊢ a ≤ c',
  'example_after': '(closed by linear arithmetic)'},
 {'name': 'norm_num',
  'summary': 'Normalises numeric expressions (multiplication, division, powers).',
  'lambda_effect': 'Replaces the goal with its numerically-normalised form.',
  'goal_effect': 'The goal closes after computing the literal values.',
  'when': 'Concrete numbers: 2 + 3 * 4 = 14, sqrt 9 = 3.',
  'example_goal': '⊢ 2 + 3 * 4 = 14',
  'example_after': '(closed by numeric normalisation)'},
 {'name': 'trivial',
  'summary': 'Tries rfl, assumption, decide — universal first attempt.',
  'lambda_effect': 'Inserts a term if any of the simple tactics succeeds.',
  'goal_effect': 'The goal closes or the tactic fails (no progress).',
  'when': 'When the goal is obvious: True, x = x, a hypothesis in context.',
  'example_goal': '⊢ True',
  'example_after': '(closed)'}]

TACTIC_INDEX = {t["name"]: t for t in TACTICS}

LEMMAS = [{'name': 'Nat.zero_add',
  'statement': '∀ n : Nat, 0 + n = n',
  'usage': 'exact Nat.zero_add n  /  rw [Nat.zero_add]',
  'summary': '0 + n = n'},
 {'name': 'Nat.add_zero',
  'statement': '∀ n : Nat, n + 0 = n',
  'usage': 'exact Nat.add_zero n  /  rw [Nat.add_zero]',
  'summary': 'n + 0 = n'},
 {'name': 'Nat.add_comm',
  'statement': '∀ a b : Nat, a + b = b + a',
  'usage': 'exact Nat.add_comm a b  /  rw [Nat.add_comm a b]',
  'summary': 'a + b = b + a'},
 {'name': 'Nat.add_assoc',
  'statement': '∀ a b c : Nat, a + b + c = a + (b + c)',
  'usage': 'exact Nat.add_assoc a b c  /  rw [Nat.add_assoc]',
  'summary': '(a + b) + c = a + (b + c)'},
 {'name': 'Nat.zero_mul',
  'statement': '∀ n : Nat, 0 * n = 0',
  'usage': 'exact Nat.zero_mul n  /  rw [Nat.zero_mul]',
  'summary': '0 * n = 0'},
 {'name': 'Nat.one_mul',
  'statement': '∀ n : Nat, 1 * n = n',
  'usage': 'exact Nat.one_mul n  /  rw [Nat.one_mul]',
  'summary': '1 * n = n'},
 {'name': 'Nat.mul_add',
  'statement': '∀ a b c : Nat, a * (b + c) = a * b + a * c',
  'usage': 'exact Nat.mul_add a b c  /  rw [Nat.mul_add]',
  'summary': 'a * (b + c) = a * b + a * c'},
 {'name': 'Nat.mul_assoc',
  'statement': '∀ a b c : Nat, a * b * c = a * (b * c)',
  'usage': 'exact Nat.mul_assoc a b c  /  rw [Nat.mul_assoc]',
  'summary': '(a * b) * c = a * (b * c)'}]

LEMMA_INDEX = {l["name"]: l for l in LEMMAS}

LIBRARY = [{'name': 'id',
  'aliases': ['I', 'identity'],
  'lambda': '\\x. x',
  'type': 'α → α',
  'lean': 'fun x => x',
  'desc': 'Identity - returns its argument unchanged; logically: `P -> P`.'},
 {'name': 'K',
  'aliases': ['const', 'konst'],
  'lambda': '\\x y. x',
  'type': 'α → β → α',
  'lean': 'fun x _ => x',
  'desc': 'Constant - takes two arguments, returns the first; logically: `P -> Q -> P`.'},
 {'name': 'const',
  'aliases': ['constant'],
  'lambda': '\\x y. x',
  'type': 'α → β → α',
  'lean': 'fun x _ => x',
  'desc': 'Synonym for K.'},
 {'name': 'S',
  'aliases': [],
  'lambda': '\\x y z. x z (y z)',
  'type': '(α → β → γ) → (α → β) → α → γ',
  'lean': 'fun x y z => x z (y z)',
  'desc': "Substitutor - distributes the argument to f and g; logically Hilbert's S."},
 {'name': 'B',
  'aliases': ['compose', 'comp'],
  'lambda': '\\f g x. f (g x)',
  'type': '(β → γ) → (α → β) → α → γ',
  'lean': 'fun f g x => f (g x)',
  'desc': 'Composition - the classic f . g; logically transitivity of implication.'},
 {'name': 'C',
  'aliases': ['flip'],
  'lambda': '\\f x y. f y x',
  'type': '(α → β → γ) → β → α → γ',
  'lean': 'fun f x y => f y x',
  'desc': 'Flip - swaps the order of two arguments.'},
 {'name': 'Y',
  'aliases': ['fix', 'fixpoint'],
  'lambda': '\\f. (\\x. f (x x)) (\\x. f (x x))',
  'type': None,
  'lean': "-- Y combinator is not typeable in STLC / Lean's type theory",
  'desc': 'Fixed point - recursion in unhypothesised lambda; untypeable in STLC.'},
 {'name': 'fst',
  'aliases': ['first', 'proj1'],
  'lambda': '\\x y. x',
  'type': 'α → β → α',
  'lean': 'fun x _ => x',
  'desc': 'First projection - alias of K (for a curried pair).'},
 {'name': 'snd',
  'aliases': ['second', 'proj2'],
  'lambda': '\\x y. y',
  'type': 'α → β → β',
  'lean': 'fun _ y => y',
  'desc': 'Second projection - K I; takes two, returns the second.'},
 {'name': 'app',
  'aliases': ['apply'],
  'lambda': '\\f x. f x',
  'type': '(α → β) → α → β',
  'lean': 'fun f x => f x',
  'desc': 'Application - explicitly `\\f x. f x`; eta-expansion of identity.'},
 {'name': 'W',
  'aliases': ['dup'],
  'lambda': '\\f x. f x x',
  'type': '(α → α → β) → α → β',
  'lean': 'fun f x => f x x',
  'desc': 'Duplicator - `\\f x. f x x`; feeds `x` to `f` twice.'},
 {'name': 'O',
  'aliases': ['owl'],
  'lambda': '\\f g. g (f g)',
  'type': None,
  'lean': "-- 'owl' nie typuje się w STLC bez polimorfizmu",
  'desc': 'Owl - `\\f g. g (f g)`; not typeable in STLC without polymorphism.'}]

LIBRARY_INDEX = {}
for _c in LIBRARY:
    LIBRARY_INDEX[_c["name"]] = _c
    for _a in _c["aliases"]:
        LIBRARY_INDEX.setdefault(_a, _c)
