"""Frozen ``ch explore`` catalog for the browser build of Lambda Lab.

Generated from the desktop JSON catalog under
``lambda_lab/lab/curry_howard/explore/data/*.json`` (16 curated theorems).
English fields only -- the browser build has no i18n; the ``*_pl`` fields
were dropped. Entry order matches the desktop loader (curated order first,
then alphabetical). Do not edit by hand; regenerate from the desktop data.
"""

THEOREMS = [{'id': 'id',
  'title': 'Identity',
  'summary': 'The simplest proof: return what you were given.',
  'type_signature': '{a : Type} -> a -> a',
  'kind': 'pure-lambda',
  'difficulty': 1,
  'lean_source': 'def ch_id {a : Type} (x : a) : a := by\n  exact x',
  'lean_term': 'fun {a : Type} (x : a) => x',
  'lambda_equivalent': '\\x. x',
  'lambda_intuition': 'Identity is the same lambda-term in STLC as in Lean.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'exact x',
                    'subterm_path': [0, 0],
                    'narrative': 'We insert variable x as the entire proof body.'}],
  'tree': {'kind': 'lam',
           'binder': 'a',
           'binder_type': 'Type',
           'implicit': True,
           'body': {'kind': 'lam',
                    'binder': 'x',
                    'binder_type': 'a',
                    'body': {'kind': 'var', 'name': 'x', 'type': 'a'}}}},
 {'id': 'K',
  'title': 'Constant combinator K',
  'summary': 'Takes two arguments, returns the first. The classic K of SKI.',
  'type_signature': '{a b : Type} -> a -> b -> a',
  'kind': 'pure-lambda',
  'difficulty': 1,
  'lean_source': 'def ch_K {a b : Type} : a -> b -> a := by\n  intro x _y\n  exact x',
  'lean_term': 'fun {a b : Type} (x : a) (_y : b) => x',
  'lambda_equivalent': '\\x y. x',
  'lambda_intuition': 'K = const. The second input is discarded (note the underscore).',
  'tactic_steps': [{'line': 2,
                    'tactic': 'intro x _y',
                    'subterm_path': [0, 0],
                    'narrative': 'We move both x and _y into context; the term gains a double '
                                 'lambda.'},
                   {'line': 3,
                    'tactic': 'exact x',
                    'subterm_path': [0, 0, 0, 0],
                    'narrative': 'The proof body = the first argument.'}],
  'tree': {'kind': 'lam',
           'binder': 'a',
           'binder_type': 'Type',
           'implicit': True,
           'body': {'kind': 'lam',
                    'binder': 'b',
                    'binder_type': 'Type',
                    'implicit': True,
                    'body': {'kind': 'lam',
                             'binder': 'x',
                             'binder_type': 'a',
                             'body': {'kind': 'lam',
                                      'binder': '_y',
                                      'binder_type': 'b',
                                      'body': {'kind': 'var', 'name': 'x', 'type': 'a'}}}}}},
 {'id': 'S',
  'title': 'Substitution combinator S',
  'summary': 'S = lambda f g x. f x (g x). Together with K it forms a complete basis (SK).',
  'type_signature': '{a b c : Type} -> (a -> b -> c) -> (a -> b) -> a -> c',
  'kind': 'pure-lambda',
  'difficulty': 3,
  'lean_source': 'def ch_S {a b c : Type} : (a -> b -> c) -> (a -> b) -> a -> c := by\n'
                 '  intro f g x\n'
                 '  exact f x (g x)',
  'lean_term': 'fun {a b c : Type} (f : a -> b -> c) (g : a -> b) (x : a) => f x (g x)',
  'lambda_equivalent': '\\f g x. f x (g x)',
  'lambda_intuition': "S threads the argument x to both f and g and feeds g's result onward to "
                      'f.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'intro f g x',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'Three lambdas introduced at once: f, g, x.'},
                   {'line': 3,
                    'tactic': 'exact f x (g x)',
                    'subterm_path': [0, 0, 0, 0, 0, 0],
                    'narrative': 'Two application nodes: ((f x) (g x)).'}],
  'tree': {'kind': 'lam',
           'binder': 'a',
           'binder_type': 'Type',
           'implicit': True,
           'body': {'kind': 'lam',
                    'binder': 'b',
                    'binder_type': 'Type',
                    'implicit': True,
                    'body': {'kind': 'lam',
                             'binder': 'c',
                             'binder_type': 'Type',
                             'implicit': True,
                             'body': {'kind': 'lam',
                                      'binder': 'f',
                                      'binder_type': 'a -> b -> c',
                                      'body': {'kind': 'lam',
                                               'binder': 'g',
                                               'binder_type': 'a -> b',
                                               'body': {'kind': 'lam',
                                                        'binder': 'x',
                                                        'binder_type': 'a',
                                                        'body': {'kind': 'app',
                                                                 'fn': {'kind': 'app',
                                                                        'fn': {'kind': 'var',
                                                                               'name': 'f',
                                                                               'type': 'a -> b '
                                                                                       '-> c'},
                                                                        'arg': {'kind': 'var',
                                                                                'name': 'x',
                                                                                'type': 'a'}},
                                                                 'arg': {'kind': 'app',
                                                                         'fn': {'kind': 'var',
                                                                                'name': 'g',
                                                                                'type': 'a -> '
                                                                                        'b'},
                                                                         'arg': {'kind': 'var',
                                                                                 'name': 'x',
                                                                                 'type': 'a'}}}}}}}}}},
 {'id': 'comp',
  'title': 'Function composition',
  'summary': 'comp f g = f . g. The classical B combinator.',
  'type_signature': '{a b c : Type} -> (b -> c) -> (a -> b) -> a -> c',
  'kind': 'pure-lambda',
  'difficulty': 2,
  'lean_source': 'def ch_comp {a b c : Type} : (b -> c) -> (a -> b) -> a -> c := by\n'
                 '  intro f g x\n'
                 '  exact f (g x)',
  'lean_term': 'fun {a b c : Type} (f : b -> c) (g : a -> b) (x : a) => f (g x)',
  'lambda_equivalent': '\\f g x. f (g x)',
  'lambda_intuition': 'We first apply g, then f - read right to left.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'intro f g x',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'Three variables introduced: f, g, x.'},
                   {'line': 3,
                    'tactic': 'exact f (g x)',
                    'subterm_path': [0, 0, 0, 0, 0, 0],
                    'narrative': 'We apply f to (g x).'}],
  'tree': {'kind': 'lam',
           'binder': 'a',
           'binder_type': 'Type',
           'implicit': True,
           'body': {'kind': 'lam',
                    'binder': 'b',
                    'binder_type': 'Type',
                    'implicit': True,
                    'body': {'kind': 'lam',
                             'binder': 'c',
                             'binder_type': 'Type',
                             'implicit': True,
                             'body': {'kind': 'lam',
                                      'binder': 'f',
                                      'binder_type': 'b -> c',
                                      'body': {'kind': 'lam',
                                               'binder': 'g',
                                               'binder_type': 'a -> b',
                                               'body': {'kind': 'lam',
                                                        'binder': 'x',
                                                        'binder_type': 'a',
                                                        'body': {'kind': 'app',
                                                                 'fn': {'kind': 'var',
                                                                        'name': 'f',
                                                                        'type': 'b -> c'},
                                                                 'arg': {'kind': 'app',
                                                                         'fn': {'kind': 'var',
                                                                                'name': 'g',
                                                                                'type': 'a -> '
                                                                                        'b'},
                                                                         'arg': {'kind': 'var',
                                                                                 'name': 'x',
                                                                                 'type': 'a'}}}}}}}}}},
 {'id': 'flip',
  'title': 'Flip - argument swap',
  'summary': 'Takes a binary function and swaps the order of its arguments.',
  'type_signature': '{a b c : Type} -> (a -> b -> c) -> b -> a -> c',
  'kind': 'pure-lambda',
  'difficulty': 2,
  'lean_source': 'def ch_flip {a b c : Type} : (a -> b -> c) -> b -> a -> c := by\n'
                 '  intro f y x\n'
                 '  exact f x y',
  'lean_term': 'fun {a b c : Type} (f : a -> b -> c) (y : b) (x : a) => f x y',
  'lambda_equivalent': '\\f y x. f x y',
  'lambda_intuition': 'The C combinator from the BCKW basis. Two app nodes, in swapped order.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'intro f y x',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'Three lambdas: f, y, x.'},
                   {'line': 3,
                    'tactic': 'exact f x y',
                    'subterm_path': [0, 0, 0, 0, 0, 0],
                    'narrative': '((f x) y) - order x then y.'}],
  'tree': {'kind': 'lam',
           'binder': 'a',
           'binder_type': 'Type',
           'implicit': True,
           'body': {'kind': 'lam',
                    'binder': 'b',
                    'binder_type': 'Type',
                    'implicit': True,
                    'body': {'kind': 'lam',
                             'binder': 'c',
                             'binder_type': 'Type',
                             'implicit': True,
                             'body': {'kind': 'lam',
                                      'binder': 'f',
                                      'binder_type': 'a -> b -> c',
                                      'body': {'kind': 'lam',
                                               'binder': 'y',
                                               'binder_type': 'b',
                                               'body': {'kind': 'lam',
                                                        'binder': 'x',
                                                        'binder_type': 'a',
                                                        'body': {'kind': 'app',
                                                                 'fn': {'kind': 'app',
                                                                        'fn': {'kind': 'var',
                                                                               'name': 'f',
                                                                               'type': 'a -> b '
                                                                                       '-> c'},
                                                                        'arg': {'kind': 'var',
                                                                                'name': 'x',
                                                                                'type': 'a'}},
                                                                 'arg': {'kind': 'var',
                                                                         'name': 'y',
                                                                         'type': 'b'}}}}}}}}},
 {'id': 'modus_ponens',
  'title': 'Modus ponens',
  'summary': 'From P and P -> Q we get Q. The most famous inference rule.',
  'type_signature': '(P Q : Prop) -> P -> (P -> Q) -> Q',
  'kind': 'prop',
  'difficulty': 2,
  'lean_source': 'theorem ch_modus_ponens (P Q : Prop) (p : P) (hpq : P -> Q) : Q := by\n'
                 '  exact hpq p',
  'lean_term': 'fun (P Q : Prop) (p : P) (hpq : P -> Q) => hpq p',
  'lambda_equivalent': '\\p hpq. hpq p',
  'lambda_intuition': 'Application: hpq applied to the proof p yields a proof of Q.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'exact hpq p',
                    'subterm_path': [0, 0, 0, 0],
                    'narrative': 'We apply hpq to p - one app node.'}],
  'tree': {'kind': 'lam',
           'binder': 'P',
           'binder_type': 'Prop',
           'body': {'kind': 'lam',
                    'binder': 'Q',
                    'binder_type': 'Prop',
                    'body': {'kind': 'lam',
                             'binder': 'p',
                             'binder_type': 'P',
                             'body': {'kind': 'lam',
                                      'binder': 'hpq',
                                      'binder_type': 'P -> Q',
                                      'body': {'kind': 'app',
                                               'fn': {'kind': 'var',
                                                      'name': 'hpq',
                                                      'type': 'P -> Q'},
                                               'arg': {'kind': 'var',
                                                       'name': 'p',
                                                       'type': 'P'}}}}}}},
 {'id': 'and_comm',
  'title': 'And-commutativity',
  'summary': 'P /\\ Q -> Q /\\ P. From a pair (p, q) we make a pair (q, p).',
  'type_signature': '(P Q : Prop) -> P /\\ Q -> Q /\\ P',
  'kind': 'prop',
  'difficulty': 2,
  'lean_source': 'theorem ch_and_comm (P Q : Prop) : P /\\ Q -> Q /\\ P := by\n'
                 '  intro h\n'
                 '  exact ⟨h.2, h.1⟩',
  'lean_term': 'fun (P Q : Prop) (h : P /\\ Q) => And.intro h.right h.left',
  'lambda_equivalent': '\\h. (snd h, fst h)',
  'lambda_intuition': 'Conjunction is a pair. Commutativity is swap. fst and snd are pair '
                      'projections.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'intro h',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'We introduce hypothesis h : P /\\ Q.'},
                   {'line': 3,
                    'tactic': 'exact ⟨h.2, h.1⟩',
                    'subterm_path': [0, 0, 0, 0],
                    'narrative': 'We build the pair: right-then-left = swap.'}],
  'tree': {'kind': 'lam',
           'binder': 'P',
           'binder_type': 'Prop',
           'body': {'kind': 'lam',
                    'binder': 'Q',
                    'binder_type': 'Prop',
                    'body': {'kind': 'lam',
                             'binder': 'h',
                             'binder_type': 'P /\\ Q',
                             'body': {'kind': 'app',
                                      'fn': {'kind': 'app',
                                             'fn': {'kind': 'const',
                                                    'name': 'And.intro',
                                                    'type': 'Q -> P -> Q /\\ P'},
                                             'arg': {'kind': 'app',
                                                     'fn': {'kind': 'const',
                                                            'name': '.right',
                                                            'type': 'Q'},
                                                     'arg': {'kind': 'var',
                                                             'name': 'h',
                                                             'type': 'P /\\ Q'}}},
                                      'arg': {'kind': 'app',
                                              'fn': {'kind': 'const',
                                                     'name': '.left',
                                                     'type': 'P'},
                                              'arg': {'kind': 'var',
                                                      'name': 'h',
                                                      'type': 'P /\\ Q'}}}}}}},
 {'id': 'or_comm',
  'title': 'Or-commutativity',
  'summary': 'P \\/ Q -> Q \\/ P. Case split: each branch repacked into the opposite '
             'constructor.',
  'type_signature': '(P Q : Prop) -> P \\/ Q -> Q \\/ P',
  'kind': 'prop',
  'difficulty': 3,
  'lean_source': 'theorem ch_or_comm (P Q : Prop) : P \\/ Q -> Q \\/ P := by\n'
                 '  intro h\n'
                 '  cases h with\n'
                 '  | inl hp => exact Or.inr hp\n'
                 '  | inr hq => exact Or.inl hq',
  'lean_term': 'fun (P Q : Prop) (h : P \\/ Q) => match h with | Or.inl hp => Or.inr hp | '
               'Or.inr hq => Or.inl hq',
  'lambda_equivalent': '\\h. match h with | inl hp -> inr hp | inr hq -> inl hq',
  'lambda_intuition': 'Disjunction is a sum type. Match picks the branch; we swap the '
                      'constructor.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'intro h',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'We introduce h : P \\/ Q.'},
                   {'line': 3,
                    'tactic': 'cases h',
                    'subterm_path': [0, 0, 0, 0],
                    'narrative': 'Eliminator for Or - two distinct arms in the term tree.'},
                   {'line': 4,
                    'tactic': 'exact Or.inr hp',
                    'subterm_path': [0, 0, 0, 0, 0],
                    'narrative': 'Left branch: we wrap hp into the right constructor.'},
                   {'line': 5,
                    'tactic': 'exact Or.inl hq',
                    'subterm_path': [0, 0, 0, 0, 1],
                    'narrative': 'Right branch: we wrap hq into the left constructor.'}],
  'tree': {'kind': 'lam',
           'binder': 'P',
           'binder_type': 'Prop',
           'body': {'kind': 'lam',
                    'binder': 'Q',
                    'binder_type': 'Prop',
                    'body': {'kind': 'lam',
                             'binder': 'h',
                             'binder_type': 'P \\/ Q',
                             'body': {'kind': 'match',
                                      'name': 'h',
                                      'arms': [{'kind': 'app',
                                                'fn': {'kind': 'const',
                                                       'name': 'Or.inr',
                                                       'type': 'P -> Q \\/ P'},
                                                'arg': {'kind': 'var',
                                                        'name': 'hp',
                                                        'type': 'P'}},
                                               {'kind': 'app',
                                                'fn': {'kind': 'const',
                                                       'name': 'Or.inl',
                                                       'type': 'Q -> Q \\/ P'},
                                                'arg': {'kind': 'var',
                                                        'name': 'hq',
                                                        'type': 'Q'}}]}}}}},
 {'id': 'not_not_intro',
  'title': 'Double negation introduction',
  'summary': 'P -> ¬¬P. Constructive; needs no excluded middle.',
  'type_signature': '(P : Prop) -> P -> not (not P)',
  'kind': 'prop',
  'difficulty': 3,
  'lean_source': 'theorem ch_not_not_intro (P : Prop) : P -> ¬¬P := by\n'
                 '  intro p np\n'
                 '  exact np p',
  'lean_term': 'fun (P : Prop) (p : P) (np : ¬P) => np p',
  'lambda_equivalent': '\\p np. np p',
  'lambda_intuition': '¬P is P -> False. Double negation is (P -> False) -> False; we apply np '
                      'to p.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'intro p np',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'We introduce p (a proof of P), then np (a negation of P).'},
                   {'line': 3,
                    'tactic': 'exact np p',
                    'subterm_path': [0, 0, 0, 0],
                    'narrative': 'np applied to p yields False, i.e., the goal ⊥.'}],
  'tree': {'kind': 'lam',
           'binder': 'P',
           'binder_type': 'Prop',
           'body': {'kind': 'lam',
                    'binder': 'p',
                    'binder_type': 'P',
                    'body': {'kind': 'lam',
                             'binder': 'np',
                             'binder_type': 'not P',
                             'body': {'kind': 'app',
                                      'fn': {'kind': 'var', 'name': 'np', 'type': 'P -> False'},
                                      'arg': {'kind': 'var', 'name': 'p', 'type': 'P'}}}}}},
 {'id': 'nat_zero_add',
  'title': '0 + n equals n',
  'summary': 'Induction on n. Left-zero of addition is not definitionally equal to n in Lean.',
  'type_signature': '(n : Nat) -> 0 + n = n',
  'kind': 'nat',
  'difficulty': 4,
  'lean_source': 'theorem ch_nat_zero_add (n : Nat) : 0 + n = n := by\n'
                 '  induction n with\n'
                 '  | zero => rfl\n'
                 '  | succ k ih => rw [Nat.add_succ, ih]',
  'lean_term': 'fun (n : Nat) => Nat.rec rfl (fun k ih => (Nat.add_succ 0 k).trans (congrArg '
               'Nat.succ ih)) n',
  'lambda_equivalent': '\\n. Nat.rec rfl (\\k ih. trans (add_succ 0 k) (cong succ ih)) n',
  'lambda_intuition': 'The term tree has two arms: the zero case (rfl) and the successor case '
                      '(rewrite + ih).',
  'tactic_steps': [{'line': 2,
                    'tactic': 'induction n',
                    'subterm_path': [0, 0],
                    'narrative': 'Induction on n - gives two goals.'},
                   {'line': 3,
                    'tactic': '| zero => rfl',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'Zero branch: 0 + 0 reduces to 0 - rfl.'},
                   {'line': 4,
                    'tactic': '| succ k ih => rw [Nat.add_succ, ih]',
                    'subterm_path': [0, 0, 1],
                    'narrative': 'Successor branch: we use Nat.add_succ and the induction '
                                 'hypothesis.'}],
  'tree': {'kind': 'lam',
           'binder': 'n',
           'binder_type': 'Nat',
           'body': {'kind': 'match',
                    'name': 'n',
                    'arms': [{'kind': 'const', 'name': 'rfl', 'type': '0 + 0 = 0'},
                             {'kind': 'app',
                              'fn': {'kind': 'app',
                                     'fn': {'kind': 'const',
                                            'name': 'Eq.trans',
                                            'type': '0 + (k+1) = k+1'},
                                     'arg': {'kind': 'const',
                                             'name': 'Nat.add_succ',
                                             'type': '0 + (k+1) = (0+k)+1'}},
                              'arg': {'kind': 'app',
                                      'fn': {'kind': 'const',
                                             'name': 'congrArg succ',
                                             'type': '(0+k)+1 = k+1'},
                                      'arg': {'kind': 'var',
                                              'name': 'ih',
                                              'type': '0 + k = k'}}}]}}},
 {'id': 'nat_add_comm',
  'title': 'Addition commutes',
  'summary': 'a + b = b + a. Here we just delegate - the full proof lives in Mathlib.',
  'type_signature': '(a b : Nat) -> a + b = b + a',
  'kind': 'nat',
  'difficulty': 5,
  'lean_source': 'theorem ch_nat_add_comm (a b : Nat) : a + b = b + a := by\n'
                 '  exact Nat.add_comm a b',
  'lean_term': 'fun (a b : Nat) => Nat.add_comm a b',
  'lambda_equivalent': '\\a b. Nat.add_comm a b',
  'lambda_intuition': 'Term-level: we just apply the existing Mathlib theorem to a and b.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'exact Nat.add_comm a b',
                    'subterm_path': [0, 0],
                    'narrative': 'Library reuse - the full induction lives in Nat.add_comm.'}],
  'tree': {'kind': 'lam',
           'binder': 'a',
           'binder_type': 'Nat',
           'body': {'kind': 'lam',
                    'binder': 'b',
                    'binder_type': 'Nat',
                    'body': {'kind': 'app',
                             'fn': {'kind': 'app',
                                    'fn': {'kind': 'const',
                                           'name': 'Nat.add_comm',
                                           'type': 'a + b = b + a'},
                                    'arg': {'kind': 'var', 'name': 'a', 'type': 'Nat'}},
                             'arg': {'kind': 'var', 'name': 'b', 'type': 'Nat'}}}}},
 {'id': 'de_morgan_pl',
  'title': 'Half of De Morgan',
  'summary': '¬(P \\/ Q) -> ¬P /\\ ¬Q. The other direction needs classical logic.',
  'type_signature': '(P Q : Prop) -> not (P \\/ Q) -> (not P) /\\ (not Q)',
  'kind': 'prop',
  'difficulty': 4,
  'lean_source': 'theorem ch_de_morgan_half (P Q : Prop) : ¬(P \\/ Q) -> ¬P /\\ ¬Q := by\n'
                 '  intro h\n'
                 '  constructor\n'
                 '  · intro p\n'
                 '    exact h (Or.inl p)\n'
                 '  · intro q\n'
                 '    exact h (Or.inr q)',
  'lean_term': 'fun (P Q : Prop) (h : ¬(P \\/ Q)) => And.intro (fun p => h (Or.inl p)) (fun q '
               '=> h (Or.inr q))',
  'lambda_equivalent': '\\h. (\\p. h (inl p), \\q. h (inr q))',
  'lambda_intuition': 'From a negated disjunction we build a pair of negations - each one '
                      'wraps a different constructor.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'intro h',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'We introduce h : ¬(P \\/ Q).'},
                   {'line': 3,
                    'tactic': 'constructor',
                    'subterm_path': [0, 0, 0],
                    'narrative': 'We split the goal into two halves - And.intro.'},
                   {'line': 4,
                    'tactic': 'intro p; exact h (Or.inl p)',
                    'subterm_path': [0, 0, 0, 0],
                    'narrative': 'Left branch: we take p and feed h applied to Or.inl p.'},
                   {'line': 5,
                    'tactic': 'intro q; exact h (Or.inr q)',
                    'subterm_path': [0, 0, 0, 1],
                    'narrative': 'Right branch: we take q and feed h applied to Or.inr q.'}],
  'tree': {'kind': 'lam',
           'binder': 'P',
           'binder_type': 'Prop',
           'body': {'kind': 'lam',
                    'binder': 'Q',
                    'binder_type': 'Prop',
                    'body': {'kind': 'lam',
                             'binder': 'h',
                             'binder_type': 'not (P \\/ Q)',
                             'body': {'kind': 'app',
                                      'fn': {'kind': 'app',
                                             'fn': {'kind': 'const',
                                                    'name': 'And.intro',
                                                    'type': '(not P) -> (not Q) -> (not P) /\\ '
                                                            '(not Q)'},
                                             'arg': {'kind': 'lam',
                                                     'binder': 'p',
                                                     'binder_type': 'P',
                                                     'body': {'kind': 'app',
                                                              'fn': {'kind': 'var',
                                                                     'name': 'h',
                                                                     'type': 'not (P \\/ Q)'},
                                                              'arg': {'kind': 'app',
                                                                      'fn': {'kind': 'const',
                                                                             'name': 'Or.inl',
                                                                             'type': 'P -> P '
                                                                                     '\\/ Q'},
                                                                      'arg': {'kind': 'var',
                                                                              'name': 'p',
                                                                              'type': 'P'}}}}},
                                      'arg': {'kind': 'lam',
                                              'binder': 'q',
                                              'binder_type': 'Q',
                                              'body': {'kind': 'app',
                                                       'fn': {'kind': 'var',
                                                              'name': 'h',
                                                              'type': 'not (P \\/ Q)'},
                                                       'arg': {'kind': 'app',
                                                               'fn': {'kind': 'const',
                                                                      'name': 'Or.inr',
                                                                      'type': 'Q -> P \\/ Q'},
                                                               'arg': {'kind': 'var',
                                                                       'name': 'q',
                                                                       'type': 'Q'}}}}}}}}},
 {'id': 'bezout',
  'title': "Bezout's identity",
  'summary': 'For every pair of natural numbers a, b their greatest common divisor can be '
             'written as an integer linear combination: gcd a b = a*x + b*y. The coefficients '
             'x and y are produced by the extended Euclidean algorithm, which tracks linear '
             'combinations of the original inputs alongside the running remainders. Mathlib '
             'provides Nat.gcdA, Nat.gcdB and the lemma Nat.gcd_eq_gcd_ab, so our proof '
             'reduces to a one-line delegation.',
  'type_signature': '(a b : Nat) -> (Nat.gcd a b : Int) = a * Nat.gcdA a b + b * Nat.gcdB a b',
  'kind': 'nat',
  'difficulty': 4,
  'lean_source': 'theorem ch_bezout (a b : Nat) : (Nat.gcd a b : Int) = a * Nat.gcdA a b + b * '
                 'Nat.gcdB a b := by\n'
                 '  exact Nat.gcd_eq_gcd_ab a b',
  'lean_term': 'fun (a b : Nat) => Nat.gcd_eq_gcd_ab a b',
  'lambda_equivalent': '(see proof term)',
  'lambda_intuition': 'The term collapses to a single Mathlib lemma applied to a and b - the '
                      'coefficients x, y live inside Nat.gcdA, Nat.gcdB.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'exact Nat.gcd_eq_gcd_ab a b',
                    'subterm_path': [0, 0],
                    'narrative': 'We delegate to Mathlib: the entire extended Euclidean '
                                 'algorithm already lives there.'}],
  'tree': {'kind': 'lam',
           'binder': 'a',
           'binder_type': 'Nat',
           'body': {'kind': 'lam',
                    'binder': 'b',
                    'binder_type': 'Nat',
                    'body': {'kind': 'app',
                             'fn': {'kind': 'app',
                                    'fn': {'kind': 'const',
                                           'name': 'Nat.gcd_eq_gcd_ab',
                                           'type': '(Nat.gcd a b : Int) = a * Nat.gcdA a b + b '
                                                   '* Nat.gcdB a b'},
                                    'arg': {'kind': 'var', 'name': 'a', 'type': 'Nat'}},
                             'arg': {'kind': 'var', 'name': 'b', 'type': 'Nat'}}}}},
 {'id': 'cauchy_schwarz_two',
  'title': 'Cauchy-Schwarz for two pairs',
  'summary': 'For real numbers a, b, x, y we have (a*x + b*y)^2 <= (a^2 + b^2)*(x^2 + y^2). '
             'The classical trick: the square of the determinant (a*y - b*x) is non-negative, '
             'and once expanded it equals exactly the gap between the right and left side of '
             'the inequality. Lean handles the rest - we feed nlinarith the hint sq_nonneg '
             '(a*y - b*x) and the tactic closes the arithmetic.',
  'type_signature': '(a b x y : Real) -> (a*x + b*y)^2 <= (a^2 + b^2) * (x^2 + y^2)',
  'kind': 'real',
  'difficulty': 3,
  'lean_source': 'theorem ch_cauchy_schwarz_two (a b x y : ℝ) :\n'
                 '    (a*x + b*y)^2 ≤ (a^2 + b^2) * (x^2 + y^2) := by\n'
                 '  nlinarith [sq_nonneg (a*y - b*x)]',
  'lean_term': 'fun (a b x y : ℝ) => nlinarith_proof_with_hint (sq_nonneg (a*y - b*x))',
  'lambda_equivalent': '(see proof term)',
  'lambda_intuition': 'The fully elaborated term is verbose - conceptually it boils down to '
                      'lifting the identity (a*y - b*x)^2 >= 0 and propagating it through the '
                      'squared inequality.',
  'tactic_steps': [{'line': 3,
                    'tactic': 'nlinarith [sq_nonneg (a*y - b*x)]',
                    'subterm_path': [0, 0, 0, 0],
                    'narrative': 'We feed nlinarith a single hint: the square of (a*y - b*x) '
                                 'is non-negative - that drives the entire proof.'}],
  'tree': {'kind': 'lam',
           'binder': 'a',
           'binder_type': 'Real',
           'body': {'kind': 'lam',
                    'binder': 'b',
                    'binder_type': 'Real',
                    'body': {'kind': 'lam',
                             'binder': 'x',
                             'binder_type': 'Real',
                             'body': {'kind': 'lam',
                                      'binder': 'y',
                                      'binder_type': 'Real',
                                      'body': {'kind': 'raw',
                                               'name': 'nlinarith [sq_nonneg (a*y - '
                                                       'b*x)]'}}}}}},
 {'id': 'euler_identity',
  'title': "Euler's identity",
  'summary': 'The equation e^(i*pi) + 1 = 0 is sometimes called the most beautiful formula in '
             'mathematics: it weaves together five constants - 0, 1, e, i, pi - and three '
             'operations: addition, multiplication, exponentiation. Mathlib carries it under '
             'the name Complex.exp_pi_mul_I, which states e^(pi*i) = -1. After rewriting and '
             'balancing signs via ring we get the target equality.',
  'type_signature': 'Complex.exp (Real.pi * Complex.I) + 1 = 0',
  'kind': 'complex',
  'difficulty': 5,
  'lean_source': 'theorem ch_euler : Complex.exp (Real.pi * Complex.I) + 1 = 0 := by\n'
                 '  rw [Complex.exp_pi_mul_I]\n'
                 '  ring',
  'lean_term': 'Eq.mpr (by rw [Complex.exp_pi_mul_I]) (by ring)',
  'lambda_equivalent': '(see proof term)',
  'lambda_intuition': 'The underlying term substitutes e^(pi*i) = -1, then the ring tactic '
                      'closes -1 + 1 = 0 - at the lambda level this is the composition of two '
                      'rewrites with a zero-equality witness.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'rw [Complex.exp_pi_mul_I]',
                    'subterm_path': [0],
                    'narrative': 'We rewrite e^(pi*i) as -1 using the prepared Mathlib lemma.'},
                   {'line': 3,
                    'tactic': 'ring',
                    'subterm_path': [0, 0],
                    'narrative': 'The remaining equation -1 + 1 = 0 is purely algebraic, so '
                                 'ring closes the goal.'}],
  'tree': {'kind': 'app',
           'fn': {'kind': 'const',
                  'name': 'Complex.exp_pi_mul_I',
                  'type': 'Complex.exp (Real.pi * Complex.I) = -1'},
           'arg': {'kind': 'raw', 'name': 'ring : (-1 : Complex) + 1 = 0'}}},
 {'id': 'fibonacci_closed',
  'title': 'Fibonacci recurrence',
  'summary': "Binet's formula gives a closed expression for the n-th Fibonacci number: fib n = "
             '(phi^n - psi^n)/sqrt 5, where phi is the golden ratio and psi its conjugate. '
             'Formalising that in Lean requires a trip through the reals and careful power '
             'arithmetic. Here we settle for the weaker statement - the recurrence fib (n+2) = '
             "fib n + fib (n+1) - and delegate to Mathlib's Nat.fib_add_two.",
  'type_signature': '(n : Nat) -> Nat.fib (n + 2) = Nat.fib n + Nat.fib (n + 1)',
  'kind': 'nat',
  'difficulty': 4,
  'lean_source': 'theorem ch_fibonacci_closed (n : Nat) : Nat.fib (n + 2) = Nat.fib n + '
                 'Nat.fib (n + 1) := by\n'
                 '  exact Nat.fib_add_two',
  'lean_term': 'fun (n : Nat) => @Nat.fib_add_two n',
  'lambda_equivalent': '(see proof term)',
  'lambda_intuition': 'The term is just an instance of an existing Mathlib induction lemma - '
                      'the recursion work lives inside the definition of Nat.fib.',
  'tactic_steps': [{'line': 2,
                    'tactic': 'exact Nat.fib_add_two',
                    'subterm_path': [0, 0],
                    'narrative': 'We delegate to Nat.fib_add_two; the remaining work is just '
                                 'lining up the induction in the signature.'}],
  'tree': {'kind': 'lam',
           'binder': 'n',
           'binder_type': 'Nat',
           'body': {'kind': 'const',
                    'name': 'Nat.fib_add_two',
                    'type': 'Nat.fib (n + 2) = Nat.fib n + Nat.fib (n + 1)'}}}]
